[package]
name = "tags_list"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dicom-core = "0.5.0"
dicom-dictionary-std = "0.5.0"
